version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      include: scope
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: chore
      include: scope
    schedule:
      interval: "weekly"
